title: Project
pages: false
files:
  sortable: true

columns:
  - width: 2/3        
    sections:
      meta:
        type: fields
        fields:

          builder:
            label: Blocks
            type: builder
            fieldsets:
            
              text:
                name: Text
                fields:
                  text:
                    label: Text
                    type: textarea
                    layout: cards
                    size: medium
                  full:
                    type: toggle
                    text:
                      - "Default width"
                      - "Fullscreen"
            
              text_image:
                name: Text + Image
                fields:
                  text:
                    label: Text
                    type: textarea
                    size: medium
                    width: 2/3
                  image:
                    label: Image
                    type: files
                    width: 1/3
                    layout: cards
                    image:
                      back: white
            
              full_image:
                name: Full-width Image
                fields:
                  image:
                    label: Image
                    type: files
                    multiple: false
                    layout: cards
                    size: huge
                    image:
                      back: white

          sections:
            label: Sections (will be deprecated)
            type: structure
            columns:
              col_1:
              col_2:
              bg_image:
            fields:
              num_cols:
                label: Columns
                type: toggle
                width: 1/2
                text:
                  - "1 column"
                  - "2 columns"
                show:
                  2: col_2
                hide:
                  1: col_2
              classes:
                type: text
                width: 1/2
                placeholder: Classes
              col_1:
                label: Text column (small)
                type: textarea
              col_2:
                label: Image column (large)
                type: textarea
              bg_colour:
                label: Section bg colour (HEX)
                type: text
                icon: magic
                width: 1/3
              bg_image:
                label: Section bg image
                type: files
                multiple: false
                width: 1/3
              bg_image_pos:
                label: Bg image position
                type: select
                width: 1/3
                default: full
                options:
                  left: "Left column"
                  right: "Right column"
                  full: "Full (as bg)"

  - width: 1/3
    sections:
      content:
        type: fields
        fields:

          year:
            label: Year
            type: text
            icon: calendar
            width: 1/3
          description:
            label: Description (1 sentence)
            type: text
          intro:
            label: Intro (a few sentences)
            type: textarea
            size: tiny
            buttons: false
          tags:
            label: Tags
            type: tags
            options: query
            query: 
              fetch: site.find('projects').children.pluck("tags", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value.slug }}"
          team:
            label: Team
            type: structure
            empty: "No team members added yet"
            columns:
              name:
                width: 1/1
            fields:
              name:
                label: Name
                type: text
                icon: user
              note:
                label: Note
                type: text
                icon: text
              link:
                label: Link
                type: url
          projecturl:
            label: Project URL
            type:  url
          keyvisual:
            label: Key visual
            type: files
            multiple: false

          h_featured:
            label: Featured
            type: headline
            width: 2/3
          featured:
            type: toggle
            width: 1/3
            options:
              0: "No"
              1: "Yes"
          featuredimage:
            label: Featured Image
            type: files
            multiple: false
            width: 1/2
          featuredcolour:
            label: Featured Color (HEX)
            type: text
            icon: magic
            width: 1/2

      files:
        label: Files
        type: files
