title: Site

columns:
	- width: 1/2
		sections:
			projects:
				headline: Projects
				type: pages
				layout: cards
				parent: site.find('projects')
				template: project
	- width: 1/2
		sections:
			listed:
				headline: Menu Pages
				type: pages
				layout: list
				status: listed
			unlisted:
				headline: Other Pages
				type: pages
				layout: list
				status: unlisted
			draft:
				headline: Draft Pages
				type: pages
				layout: list
				status: draft
				create: 
					- default
					- projects
					- cv
					- articles
			options:
				type: fields
				fields:
					theme:
						label: Site theme
						type: radio
						default: ldaniel
						options:
							ldaniel: ldaniel.eu
							sincere: Sincere—Studio

					title_prefix:
						label: Page title prefix
						type: text
						default: §
						help: Appears as the page title
